const pages = {
  loginPath: "/auth/login",
  homePagePath: "/",
  ticketsPath: "/tickets",
  ticketDetailPath: "/tickets/:id",
  editTicketPath: "/tickets/:id/edit",
  addTicketPath: "/tickets/add",
  ticketsPathForInstitution: "/tickets_institution",
  editTicketPathForInstitution: "/tickets_institution/:id/edit",
  addTicketPathForInstitution: "/tickets_institution/add",
  ticketPathForInstitution: "/tickets_institution/:id",
  usersPath: "/users",
  userDetailPath: "/users/:id",
  editUserPath: "/users/:id/edit",
  addUsersPath: "/users/add",
  institutionsPath: "/institutions",
  institutionDetailPath: "/institutions/:id",
  lockerForInstitutionPath: "/institutions/:id/lockers",
  editInstitutionPath: "/institutions/:id/edit",
  addInstitutionPath: "/institutions/add",
  lockersPath: "/lockers",
  lockerDetailPath: "/lockers/:id",
  editLockerPath: "/lockers/:id/edit",
  addLockerPath: "/lockers/add",
  purchasePath: "/purchase",
  purchaseDetailPath: "/purchase/:id",
  purchasePathForInstitution: "/purchase_institution",
  purchaseDetailPathForInstitution: "/purchase_institution/:id",
  accessDenied: "/access-denied",
};

export default pages;
